// モックグランドデータ

export interface MockGround {
  id: string;
  name: string;
  facilityName: string;
  prefecture: string;
  city: string;
  address: string;
  groundType: "天然芝" | "人工芝" | "土" | "室内";
  size: "11人制" | "8人制" | "フットサル";
  capacity?: number;
  hourlyRate: number;
  parkingCapacity?: number; // 駐車場の台数
  showerCount?: number; // シャワーの数
  nearestStation?: string; // 最寄駅
  stationDistance?: number; // 最寄駅からの距離（徒歩分）
  imageUrl?: string;
  availableSlots: string[];
  amenities: string[];
  description: string;
  accessInfo: string;
}

export const mockGrounds: MockGround[] = [
  {
    id: "1",
    name: "Aコート",
    facilityName: "東京スポーツパーク",
    prefecture: "東京都",
    city: "渋谷区",
    address: "東京都渋谷区恵比寿1-2-3",
    groundType: "人工芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 8000,
    parkingCapacity: 50,
    showerCount: 8,
    nearestStation: "JR恵比寿駅",
    stationDistance: 5,
    availableSlots: ["10:00-12:00", "14:00-16:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "自動販売機", "ロッカー"],
    description: "都心からアクセス抜群の人工芝グランド。最新の人工芝を使用しており、天然芝に近い感覚でプレーできます。",
    accessInfo: "JR恵比寿駅 西口より徒歩5分",
  },
  {
    id: "2",
    name: "Bコート",
    facilityName: "東京スポーツパーク",
    prefecture: "東京都",
    city: "渋谷区",
    address: "東京都渋谷区恵比寿1-2-3",
    groundType: "天然芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 10000,
    parkingCapacity: 50,
    showerCount: 6,
    nearestStation: "JR恵比寿駅",
    stationDistance: 5,
    availableSlots: ["09:00-11:00", "13:00-15:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ロッカー"],
    description: "天然芝の本格的なグランド。公式戦にも対応しています。",
    accessInfo: "JR恵比寿駅 西口より徒歩5分",
  },
  {
    id: "3",
    name: "メインコート",
    facilityName: "代々木フットボールセンター",
    prefecture: "東京都",
    city: "渋谷区",
    address: "東京都渋谷区代々木2-1-1",
    groundType: "人工芝",
    size: "8人制",
    capacity: 150,
    hourlyRate: 6000,
    parkingCapacity: 30,
    showerCount: 4,
    nearestStation: "JR代々木駅",
    stationDistance: 3,
    availableSlots: ["10:00-12:00", "15:00-17:00", "18:00-20:00"],
    amenities: ["駐車場", "更衣室", "自動販売機"],
    description: "8人制に最適なサイズのグランド。ジュニアチームの練習に人気です。",
    accessInfo: "JR代々木駅 北口より徒歩3分",
  },
  {
    id: "4",
    name: "フットサルコート",
    facilityName: "渋谷スポーツアリーナ",
    prefecture: "東京都",
    city: "渋谷区",
    address: "東京都渋谷区神南1-5-8",
    groundType: "室内",
    size: "フットサル",
    capacity: 50,
    hourlyRate: 4000,
    parkingCapacity: 15,
    showerCount: 4,
    nearestStation: "JR渋谷駅",
    stationDistance: 8,
    availableSlots: ["11:00-13:00", "13:00-15:00", "17:00-19:00", "19:00-21:00"],
    amenities: ["更衣室", "シャワー", "ナイター照明", "自動販売機"],
    description: "完全室内のフットサルコート。天候に左右されずプレーできます。",
    accessInfo: "JR渋谷駅 ハチ公口より徒歩8分",
  },
  {
    id: "5",
    name: "グリーンフィールド",
    facilityName: "世田谷総合運動場",
    prefecture: "東京都",
    city: "世田谷区",
    address: "東京都世田谷区大蔵4-6-1",
    groundType: "天然芝",
    size: "11人制",
    capacity: 300,
    hourlyRate: 12000,
    parkingCapacity: 100,
    showerCount: 12,
    nearestStation: "東急田園都市線 用賀駅",
    stationDistance: 20,
    availableSlots: ["09:00-11:00", "11:00-13:00", "14:00-16:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店"],
    description: "広々とした天然芝のグランド。大会開催にも対応可能です。",
    accessInfo: "東急田園都市線 用賀駅より徒歩20分、バスあり",
  },
  {
    id: "6",
    name: "サブグラウンド",
    facilityName: "横浜スポーツパーク",
    prefecture: "神奈川県",
    city: "横浜市",
    address: "神奈川県横浜市港北区新横浜3-10-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 250,
    hourlyRate: 7500,
    parkingCapacity: 80,
    showerCount: 10,
    nearestStation: "JR新横浜駅",
    stationDistance: 7,
    availableSlots: ["10:00-12:00", "13:00-15:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "新横浜駅から近くアクセス抜群。人工芝で雨天時も利用可能です。",
    accessInfo: "JR新横浜駅より徒歩7分",
  },
  {
    id: "7",
    name: "フットサルコート1",
    facilityName: "川崎フットサルパーク",
    prefecture: "神奈川県",
    city: "川崎市",
    address: "神奈川県川崎市中原区小杉町3-600",
    groundType: "人工芝",
    size: "フットサル",
    capacity: 40,
    hourlyRate: 3500,
    parkingCapacity: 20,
    showerCount: 6,
    nearestStation: "JR武蔵小杉駅",
    stationDistance: 5,
    availableSlots: ["12:00-14:00", "14:00-16:00", "18:00-20:00", "20:00-22:00"],
    amenities: ["更衣室", "シャワー", "ナイター照明", "自動販売機", "ロッカー"],
    description: "武蔵小杉駅近くの人気フットサルコート。夜間も利用可能です。",
    accessInfo: "JR武蔵小杉駅より徒歩5分",
  },
  {
    id: "8",
    name: "人工芝グラウンド",
    facilityName: "大阪舞洲スポーツアイランド",
    prefecture: "大阪府",
    city: "大阪市",
    address: "大阪府大阪市此花区北港緑地2-1-89",
    groundType: "人工芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 6500,
    parkingCapacity: 150,
    showerCount: 8,
    nearestStation: "大阪市営地下鉄 コスモスクエア駅",
    stationDistance: 15,
    availableSlots: ["09:00-11:00", "11:00-13:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "売店"],
    description: "大阪湾に面した開放的なスポーツ施設。駐車場完備で車でのアクセスも便利。",
    accessInfo: "大阪市営地下鉄 コスモスクエア駅よりバス15分",
  },
  // 東京都 - 千代田区
  {
    id: "9",
    name: "皇居外苑グラウンド",
    facilityName: "千代田スポーツセンター",
    prefecture: "東京都",
    city: "千代田区",
    address: "東京都千代田区内幸町1-1-1",
    groundType: "人工芝",
    size: "8人制",
    capacity: 120,
    hourlyRate: 9000,
    parkingCapacity: 25,
    showerCount: 4,
    nearestStation: "東京メトロ 日比谷駅",
    stationDistance: 3,
    availableSlots: ["10:00-12:00", "14:00-16:00"],
    amenities: ["更衣室", "シャワー", "ロッカー", "自動販売機"],
    description: "都心の好立地。ビジネス街でアクセス抜群のグラウンドです。",
    accessInfo: "東京メトロ日比谷駅より徒歩3分",
  },
  // 東京都 - 中央区
  {
    id: "10",
    name: "月島フットサルコート",
    facilityName: "中央区スポーツプラザ",
    prefecture: "東京都",
    city: "中央区",
    address: "東京都中央区月島3-4-1",
    groundType: "室内",
    size: "フットサル",
    capacity: 60,
    hourlyRate: 5000,
    parkingCapacity: 20,
    showerCount: 6,
    nearestStation: "東京メトロ 月島駅",
    stationDistance: 2,
    availableSlots: ["12:00-14:00", "16:00-18:00", "18:00-20:00"],
    amenities: ["更衣室", "シャワー", "ナイター照明", "自動販売機"],
    description: "月島駅直結の室内フットサルコート。雨天時も安心してプレーできます。",
    accessInfo: "東京メトロ月島駅より徒歩2分",
  },
  // 東京都 - 港区
  {
    id: "11",
    name: "お台場サッカーフィールド",
    facilityName: "港区スポーツセンター",
    prefecture: "東京都",
    city: "港区",
    address: "東京都港区台場1-7-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 250,
    hourlyRate: 11000,
    parkingCapacity: 100,
    showerCount: 10,
    nearestStation: "ゆりかもめ お台場海浜公園駅",
    stationDistance: 5,
    availableSlots: ["09:00-11:00", "13:00-15:00", "17:00-19:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店"],
    description: "海辺の開放的なロケーション。大会開催にも最適です。",
    accessInfo: "ゆりかもめ お台場海浜公園駅より徒歩5分",
  },
  // 東京都 - 新宿区
  {
    id: "12",
    name: "新宿中央グラウンド",
    facilityName: "新宿スポーツセンター",
    prefecture: "東京都",
    city: "新宿区",
    address: "東京都新宿区大久保3-1-2",
    groundType: "人工芝",
    size: "8人制",
    capacity: 150,
    hourlyRate: 7500,
    parkingCapacity: 40,
    showerCount: 8,
    nearestStation: "JR 新大久保駅",
    stationDistance: 8,
    availableSlots: ["10:00-12:00", "14:00-16:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "新宿区の総合スポーツ施設内。8人制に最適なグラウンドです。",
    accessInfo: "JR新大久保駅より徒歩8分",
  },
  // 東京都 - 文京区
  {
    id: "13",
    name: "小石川運動場",
    facilityName: "文京総合体育館",
    prefecture: "東京都",
    city: "文京区",
    address: "東京都文京区後楽1-7-5",
    groundType: "天然芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 10500,
    parkingCapacity: 30,
    showerCount: 6,
    nearestStation: "東京メトロ 後楽園駅",
    stationDistance: 6,
    availableSlots: ["09:00-11:00", "11:00-13:00"],
    amenities: ["駐車場", "更衣室", "シャワー"],
    description: "東京ドーム近くの天然芝グラウンド。公式戦開催実績多数。",
    accessInfo: "東京メトロ後楽園駅より徒歩6分",
  },
  // 東京都 - 台東区
  {
    id: "14",
    name: "隅田川河川敷グラウンド",
    facilityName: "台東区スポーツ広場",
    prefecture: "東京都",
    city: "台東区",
    address: "東京都台東区花川戸2-1-1",
    groundType: "土",
    size: "11人制",
    capacity: 100,
    hourlyRate: 4500,
    parkingCapacity: 20,
    showerCount: 2,
    nearestStation: "東京メトロ 浅草駅",
    stationDistance: 10,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室"],
    description: "河川敷の開放的なグラウンド。リーズナブルな料金設定です。",
    accessInfo: "東京メトロ浅草駅より徒歩10分",
  },
  // 東京都 - 墨田区
  {
    id: "15",
    name: "錦糸町フットサルパーク",
    facilityName: "墨田区総合体育館",
    prefecture: "東京都",
    city: "墨田区",
    address: "東京都墨田区錦糸4-15-1",
    groundType: "人工芝",
    size: "フットサル",
    capacity: 50,
    hourlyRate: 4200,
    parkingCapacity: 35,
    showerCount: 4,
    nearestStation: "JR 錦糸町駅",
    stationDistance: 5,
    availableSlots: ["12:00-14:00", "16:00-18:00", "19:00-21:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "自動販売機"],
    description: "錦糸町駅近くの人気フットサルコート。夜間も利用可能。",
    accessInfo: "JR錦糸町駅より徒歩5分",
  },
  // 東京都 - 江東区
  {
    id: "16",
    name: "夢の島競技場",
    facilityName: "夢の島公園",
    prefecture: "東京都",
    city: "江東区",
    address: "東京都江東区夢の島2-1-3",
    groundType: "天然芝",
    size: "11人制",
    capacity: 300,
    hourlyRate: 12000,
    parkingCapacity: 120,
    showerCount: 12,
    nearestStation: "東京メトロ 新木場駅",
    stationDistance: 7,
    availableSlots: ["09:00-11:00", "11:00-13:00", "14:00-16:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店", "ロッカー"],
    description: "広大な公園内の本格的な競技場。大会運営に最適です。",
    accessInfo: "東京メトロ新木場駅より徒歩7分",
  },
  // 東京都 - 品川区
  {
    id: "17",
    name: "大井ふ頭グラウンド",
    facilityName: "品川区スポーツ広場",
    prefecture: "東京都",
    city: "品川区",
    address: "東京都品川区八潮5-5-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 180,
    hourlyRate: 8500,
    parkingCapacity: 80,
    showerCount: 8,
    nearestStation: "東京モノレール 大井競馬場前駅",
    stationDistance: 12,
    availableSlots: ["10:00-12:00", "13:00-15:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "湾岸エリアの広々としたグラウンド。駐車場完備で車でのアクセスも便利。",
    accessInfo: "東京モノレール大井競馬場前駅より徒歩12分",
  },
  // 東京都 - 目黒区
  {
    id: "18",
    name: "駒場運動場",
    facilityName: "目黒区スポーツセンター",
    prefecture: "東京都",
    city: "目黒区",
    address: "東京都目黒区駒場2-19-59",
    groundType: "人工芝",
    size: "8人制",
    capacity: 130,
    hourlyRate: 7000,
    parkingCapacity: 25,
    showerCount: 6,
    nearestStation: "京王井の頭線 駒場東大前駅",
    stationDistance: 8,
    availableSlots: ["10:00-12:00", "14:00-16:00"],
    amenities: ["駐車場", "更衣室", "シャワー"],
    description: "閑静な住宅街にあるスポーツ施設。ジュニア育成に最適です。",
    accessInfo: "京王井の頭線駒場東大前駅より徒歩8分",
  },
  // 東京都 - 大田区
  {
    id: "19",
    name: "大森スポーツグラウンド",
    facilityName: "大田区総合体育館",
    prefecture: "東京都",
    city: "大田区",
    address: "東京都大田区大森北4-16-5",
    groundType: "人工芝",
    size: "11人制",
    capacity: 220,
    hourlyRate: 8800,
    parkingCapacity: 60,
    showerCount: 10,
    nearestStation: "JR 大森駅",
    stationDistance: 10,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "自動販売機"],
    description: "大田区最大級のスポーツ施設。充実した設備が魅力です。",
    accessInfo: "JR大森駅より徒歩10分",
  },
  // 東京都 - 中野区
  {
    id: "20",
    name: "中野サンプラザグラウンド",
    facilityName: "中野区スポーツ公園",
    prefecture: "東京都",
    city: "中野区",
    address: "東京都中野区中野4-10-1",
    groundType: "人工芝",
    size: "8人制",
    capacity: 140,
    hourlyRate: 6800,
    parkingCapacity: 40,
    showerCount: 6,
    nearestStation: "JR 中野駅",
    stationDistance: 6,
    availableSlots: ["10:00-12:00", "14:00-16:00", "18:00-20:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "中野駅から好アクセス。8人制サッカーに最適なグラウンドです。",
    accessInfo: "JR中野駅より徒歩6分",
  },
  // 東京都 - 杉並区
  {
    id: "21",
    name: "善福寺公園グラウンド",
    facilityName: "杉並区運動場",
    prefecture: "東京都",
    city: "杉並区",
    address: "東京都杉並区善福寺3-9-10",
    groundType: "天然芝",
    size: "11人制",
    capacity: 180,
    hourlyRate: 9500,
    parkingCapacity: 50,
    showerCount: 8,
    nearestStation: "JR 荻窪駅",
    stationDistance: 15,
    availableSlots: ["09:00-11:00", "11:00-13:00", "14:00-16:00"],
    amenities: ["駐車場", "更衣室", "シャワー"],
    description: "公園内の緑豊かな天然芝グラウンド。自然環境の中でプレーできます。",
    accessInfo: "JR荻窪駅よりバス10分",
  },
  // 東京都 - 豊島区
  {
    id: "22",
    name: "池袋フットサルアリーナ",
    facilityName: "豊島区スポーツセンター",
    prefecture: "東京都",
    city: "豊島区",
    address: "東京都豊島区東池袋4-5-2",
    groundType: "室内",
    size: "フットサル",
    capacity: 70,
    hourlyRate: 5500,
    parkingCapacity: 30,
    showerCount: 8,
    nearestStation: "JR 池袋駅",
    stationDistance: 7,
    availableSlots: ["12:00-14:00", "14:00-16:00", "18:00-20:00", "20:00-22:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "ロッカー", "自動販売機"],
    description: "池袋駅近くの室内フットサルコート。最新設備を完備しています。",
    accessInfo: "JR池袋駅より徒歩7分",
  },
  // 東京都 - 北区
  {
    id: "23",
    name: "赤羽スポーツの森",
    facilityName: "北区総合運動場",
    prefecture: "東京都",
    city: "北区",
    address: "東京都北区赤羽西6-24-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 8200,
    parkingCapacity: 70,
    showerCount: 10,
    nearestStation: "JR 赤羽駅",
    stationDistance: 12,
    availableSlots: ["09:00-11:00", "13:00-15:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店"],
    description: "総合運動場内の本格的なグラウンド。大会開催実績も豊富です。",
    accessInfo: "JR赤羽駅よりバス8分",
  },
  // 東京都 - 荒川区
  {
    id: "24",
    name: "荒川河川敷運動公園",
    facilityName: "荒川区スポーツ広場",
    prefecture: "東京都",
    city: "荒川区",
    address: "東京都荒川区南千住8-5-1",
    groundType: "土",
    size: "11人制",
    capacity: 120,
    hourlyRate: 4000,
    parkingCapacity: 40,
    showerCount: 4,
    nearestStation: "東京メトロ 南千住駅",
    stationDistance: 8,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー"],
    description: "荒川河川敷の開放的なグラウンド。リーズナブルな料金が魅力です。",
    accessInfo: "東京メトロ南千住駅より徒歩8分",
  },
  // 東京都 - 板橋区
  {
    id: "25",
    name: "城北中央公園グラウンド",
    facilityName: "板橋区運動場",
    prefecture: "東京都",
    city: "板橋区",
    address: "東京都板橋区小茂根1-1-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 190,
    hourlyRate: 7800,
    parkingCapacity: 55,
    showerCount: 8,
    nearestStation: "東京メトロ 小竹向原駅",
    stationDistance: 10,
    availableSlots: ["10:00-12:00", "13:00-15:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "広大な公園内のグラウンド。緑に囲まれた環境でプレーできます。",
    accessInfo: "東京メトロ小竹向原駅より徒歩10分",
  },
  // 東京都 - 練馬区
  {
    id: "26",
    name: "光が丘公園サッカー場",
    facilityName: "練馬区総合運動場",
    prefecture: "東京都",
    city: "練馬区",
    address: "東京都練馬区光が丘4-1-1",
    groundType: "天然芝",
    size: "11人制",
    capacity: 250,
    hourlyRate: 10000,
    parkingCapacity: 90,
    showerCount: 12,
    nearestStation: "都営大江戸線 光が丘駅",
    stationDistance: 8,
    availableSlots: ["09:00-11:00", "11:00-13:00", "14:00-16:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店", "ロッカー"],
    description: "練馬区最大の公園内にある本格的な天然芝グラウンド。",
    accessInfo: "都営大江戸線光が丘駅より徒歩8分",
  },
  // 東京都 - 足立区
  {
    id: "27",
    name: "舎人公園陸上競技場",
    facilityName: "足立区総合スポーツセンター",
    prefecture: "東京都",
    city: "足立区",
    address: "東京都足立区舎人公園1-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 280,
    hourlyRate: 8500,
    parkingCapacity: 100,
    showerCount: 12,
    nearestStation: "日暮里・舎人ライナー 舎人公園駅",
    stationDistance: 3,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店"],
    description: "陸上競技場を併設する本格施設。大会開催に最適です。",
    accessInfo: "日暮里・舎人ライナー舎人公園駅より徒歩3分",
  },
  // 東京都 - 葛飾区
  {
    id: "28",
    name: "奥戸総合スポーツセンター",
    facilityName: "葛飾区総合スポーツセンター",
    prefecture: "東京都",
    city: "葛飾区",
    address: "東京都葛飾区奥戸7-17-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 7500,
    parkingCapacity: 80,
    showerCount: 10,
    nearestStation: "JR 新小岩駅",
    stationDistance: 15,
    availableSlots: ["10:00-12:00", "13:00-15:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "自動販売機"],
    description: "葛飾区の総合スポーツ施設。充実した設備と駐車場を完備。",
    accessInfo: "JR新小岩駅よりバス10分",
  },
  // 東京都 - 江戸川区
  {
    id: "29",
    name: "江戸川河川敷グラウンド",
    facilityName: "江戸川区陸上競技場",
    prefecture: "東京都",
    city: "江戸川区",
    address: "東京都江戸川区西葛西8-1-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 220,
    hourlyRate: 7800,
    parkingCapacity: 70,
    showerCount: 8,
    nearestStation: "東京メトロ 西葛西駅",
    stationDistance: 10,
    availableSlots: ["09:00-11:00", "11:00-13:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "河川敷の広々としたグラウンド。眺望の良い開放的な環境です。",
    accessInfo: "東京メトロ西葛西駅より徒歩10分",
  },
  // 東京都 - 八王子市
  {
    id: "30",
    name: "富士森公園陸上競技場",
    facilityName: "八王子市総合運動場",
    prefecture: "東京都",
    city: "八王子市",
    address: "東京都八王子市台町2-2-1",
    groundType: "天然芝",
    size: "11人制",
    capacity: 350,
    hourlyRate: 9000,
    parkingCapacity: 150,
    showerCount: 14,
    nearestStation: "JR 八王子駅",
    stationDistance: 15,
    availableSlots: ["09:00-11:00", "11:00-13:00", "14:00-16:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店", "ロッカー"],
    description: "八王子市最大の総合運動場。Jリーグの練習場としても使用実績あり。",
    accessInfo: "JR八王子駅よりバス10分",
  },
  // 東京都 - 立川市
  {
    id: "31",
    name: "立川公園サッカー場",
    facilityName: "立川市総合体育館",
    prefecture: "東京都",
    city: "立川市",
    address: "東京都立川市泉町786-11",
    groundType: "人工芝",
    size: "11人制",
    capacity: 240,
    hourlyRate: 8000,
    parkingCapacity: 100,
    showerCount: 10,
    nearestStation: "JR 立川駅",
    stationDistance: 12,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店"],
    description: "多摩地区を代表する総合スポーツ施設。交通アクセスも良好です。",
    accessInfo: "JR立川駅よりバス8分",
  },
  // 東京都 - 武蔵野市
  {
    id: "32",
    name: "武蔵野中央公園グラウンド",
    facilityName: "武蔵野市総合体育館",
    prefecture: "東京都",
    city: "武蔵野市",
    address: "東京都武蔵野市八幡町2-4-22",
    groundType: "人工芝",
    size: "8人制",
    capacity: 160,
    hourlyRate: 7200,
    parkingCapacity: 45,
    showerCount: 6,
    nearestStation: "JR 三鷹駅",
    stationDistance: 10,
    availableSlots: ["10:00-12:00", "14:00-16:00", "16:00-18:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "武蔵野市の中心部にある人気のグラウンド。ジュニア層に人気です。",
    accessInfo: "JR三鷹駅よりバス7分",
  },
  // 東京都 - 三鷹市
  {
    id: "33",
    name: "三鷹中央防災公園グラウンド",
    facilityName: "三鷹市スポーツセンター",
    prefecture: "東京都",
    city: "三鷹市",
    address: "東京都三鷹市新川6-37-1",
    groundType: "人工芝",
    size: "11人制",
    capacity: 200,
    hourlyRate: 8300,
    parkingCapacity: 60,
    showerCount: 8,
    nearestStation: "JR 三鷹駅",
    stationDistance: 18,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明"],
    description: "防災公園内の広々としたグラウンド。安全性も考慮された施設です。",
    accessInfo: "JR三鷹駅よりバス12分",
  },
  // 東京都 - 府中市
  {
    id: "34",
    name: "府中市民陸上競技場",
    facilityName: "府中市総合体育館",
    prefecture: "東京都",
    city: "府中市",
    address: "東京都府中市浅間町1-3-1",
    groundType: "天然芝",
    size: "11人制",
    capacity: 300,
    hourlyRate: 9500,
    parkingCapacity: 120,
    showerCount: 12,
    nearestStation: "京王線 東府中駅",
    stationDistance: 8,
    availableSlots: ["09:00-11:00", "11:00-13:00", "14:00-16:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店", "ロッカー"],
    description: "府中市の総合陸上競技場。天然芝の本格的なグラウンドです。",
    accessInfo: "京王線東府中駅より徒歩8分",
  },
  // 東京都 - 調布市
  {
    id: "35",
    name: "味の素スタジアム西競技場",
    facilityName: "調布市総合体育館",
    prefecture: "東京都",
    city: "調布市",
    address: "東京都調布市西町376-3",
    groundType: "人工芝",
    size: "11人制",
    capacity: 280,
    hourlyRate: 10500,
    parkingCapacity: 200,
    showerCount: 16,
    nearestStation: "京王線 飛田給駅",
    stationDistance: 5,
    availableSlots: ["09:00-11:00", "13:00-15:00", "15:00-17:00", "17:00-19:00"],
    amenities: ["駐車場", "更衣室", "シャワー", "ナイター照明", "売店", "ロッカー", "自動販売機"],
    description: "味の素スタジアムに隣接する本格的なグラウンド。プロレベルの施設です。",
    accessInfo: "京王線飛田給駅より徒歩5分",
  },
];

// フィルタリング関数
export function filterGrounds(
  grounds: MockGround[],
  filters: {
    prefecture?: string;
    city?: string;
    size?: string;
    groundType?: string;
  }
): MockGround[] {
  return grounds.filter((ground) => {
    if (filters.prefecture && ground.prefecture !== filters.prefecture) return false;
    if (filters.city && ground.city !== filters.city) return false;
    if (filters.size && filters.size !== "すべて" && ground.size !== filters.size) return false;
    if (filters.groundType && filters.groundType !== "すべて" && ground.groundType !== filters.groundType)
      return false;
    return true;
  });
}

// ソート関数
export function sortGrounds(
  grounds: MockGround[],
  sortBy: "recommended" | "price-low" | "price-high" | "distance"
): MockGround[] {
  const sorted = [...grounds];

  switch (sortBy) {
    case "price-low":
      return sorted.sort((a, b) => a.hourlyRate - b.hourlyRate);
    case "price-high":
      return sorted.sort((a, b) => b.hourlyRate - a.hourlyRate);
    case "distance":
      // 距離でのソートは将来的に位置情報を使って実装
      return sorted;
    case "recommended":
    default:
      // おすすめ順（現状はそのまま）
      return sorted;
  }
}

// IDでグランドを取得
export function getGroundById(id: string): MockGround | undefined {
  return mockGrounds.find((ground) => ground.id === id);
}
